Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print a
NameError: name 'a' is not defined
