Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at Main.main(Unknown Source)
